export const getParameterFields = (itemData) => {
    return [{
        col: 4,
        callback: itemData.callback,
        disabled: itemData.disabled,
        groups: [{
            type: "text",
            id: "inputParameterName",
            label: "Name",
            name: "name",
            // options: itemData.options[0],
            control: "input",
            // isSubmit: itemData.isSubmit,
            isRequired:true,
            itemVal: itemData.values ? itemData.values["name"] : '',
        },
        {
            type: "text",
            id: "inputParameterContext",
            label: "Context",
            name: "context",
            // options: itemData.options[0],
            control: "input",
            // isSubmit: itemData.isSubmit,
            isRequired:true,
            itemVal: itemData.values ? itemData.values["context"] : '',
        },
        {
            type: "text",
            id: "inputParameterDisplay_name",
            label: "Display Name",
            name: "display_name",
            // options: itemData.options[0],
            control: "input",
            // isSubmit: itemData.isSubmit,
            isRequired: true,
            itemVal: itemData.values ? itemData.values["display_name"] : '',
        },
        {
            type: "text",
            id: "inputParameterDescription",
            label: "Description",
            name: "description",
            // options: itemData.options[0],
            control: "input",
            isSubmit: itemData.isSubmit,
            isRequired: true,
            itemVal: itemData.values ? itemData.values["description"] : '',
        },
        {
            type: "text",
            id: "inputParameterType",
            label: "Type",
            name: "type",
            // options: itemData.options[0],
            control: "input",
            isSubmit: itemData.isSubmit,
            isRequired: true,
            itemVal: itemData.values ? itemData.values["type"] : '',
        },
        {
            type: "text",
            id: "inputParameterResource",
            label: "Resource",
            name: "resource",
            // options: itemData.options[0],
            control: "input",
            isSubmit: itemData.isSubmit,
            isRequired:true,
            itemVal: itemData.values ? itemData.values["resource"] : '',
        },
        {
            // type: "text",
            id: "inputParameterResource",
            label: "Step",
            name: "step_id",
            options: itemData.options[0],
            control: "select",
            isSubmit: itemData.isSubmit,
            isRequired: !itemData?.values?.step_id,
            itemVal: itemData.values ? itemData.values["step_id"] : '',
        },
       
        ]
    } 
    ];
}